# Generated by Django 4.1.4 on 2022-12-20 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cajaNombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCajero', models.CharField(max_length=100, verbose_name='Nombre')),
                ('paterno', models.CharField(max_length=200, verbose_name='Paterno')),
                ('materno', models.CharField(max_length=200, verbose_name='Materno')),
                ('Fechanac', models.DateTimeField(default=datetime.datetime.now)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clienteName', models.CharField(max_length=200)),
                ('clientePaterno', models.CharField(max_length=200)),
                ('clienteMaterno', models.CharField(max_length=200)),
                ('clienteFecha', models.DateTimeField(default=datetime.datetime.now)),
                ('clienteTelefono', models.CharField(max_length=200)),
                ('fotocliente', models.ImageField(blank=True, null=True, upload_to='fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicioNombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursalNombre', models.CharField(max_length=200)),
                ('sucursalDireccion', models.CharField(max_length=200)),
                ('sucursalHorario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroticket', models.IntegerField(blank=True, null=True)),
                ('fechayhora', models.DateTimeField(default=datetime.datetime.now)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.caja', verbose_name='Caja ok')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cajero', verbose_name='Cajero ok')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente', verbose_name='Cliente ok')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sucursal', verbose_name='Sucursal ok')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atencionNombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TicketServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicio', verbose_name='Servicio requerido')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ticket', verbose_name='Ticket')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipoAtencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipoatencion', verbose_name='Tipoatencion ok'),
        ),
        migrations.AddIndex(
            model_name='ticketservicio',
            index=models.Index(fields=['ticket', 'servicio'], name='api_tickets_ticket__7dee6c_idx'),
        ),
    ]
