# Generated by Django 4.1.4 on 2022-12-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_cajero_fechanac'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='sucursalCiudad',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
