# Generated by Django 4.1.4 on 2022-12-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_sucursal_sucursalciudad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='clienteFecha',
        ),
        migrations.AddField(
            model_name='cliente',
            name='clienteFechanac',
            field=models.DateField(null=True),
        ),
    ]
