# Generated by Django 4.1.4 on 2022-12-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_ticket_caja_alter_ticket_cajero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='nroticket',
            field=models.CharField(max_length=200),
        ),
    ]
